apiRules:
- include: # The namespaces to generate
    uidRegex: ^Doji\.AI\.Segmentation
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: ^Doji\.AI\.Segmentation\.Editor
- exclude:
    uidRegex: ^Doji\.AI\.Segmentation\.Samples